/*
 * xthreads_errors.h
 *
 *  Created on: 1 Aug 2016
 *      Author: Matthew
 */


#ifndef XTHREADS_ERRORS_H_
#define XTHREADS_ERRORS_H_

#define XTHREADS_ENONE 0xf0
#define XTHREADS_EBUSY XTHREADS_ENONE+1
#define XTHREADS_EUNDEFINED XTHREADS_EBUSY+1
#define XTHREADS_EPERM XTHREADS_EUNDEFINED+1
#define XTHREADS_ENOMEM XTHREADS_EPERM+1
#define XTHREADS_EAGAIN XTHREADS_ENOMEM+1
#define XTHREADS_ETIMEDOUT XTHREADS_EAGAIN+1
#define XTHREADS_EDEADLK XTHREADS_ETIMEDOUT+1
#define XTHREADS_ECANCELLED XTHREADS_EDEADLK+1
#define XTHREADS_EINVAL XTHREADS_ECANCELLED+1

#endif /* XTHREADS_ERRORS_H_ */
